### Exercise 1 - Lesson 3 Data Preprocessing

#### Please put your details here.

#### Last name: Viernes
#### First name: Marc Peejay
#### Student number: 2020-10139
#### Section: WFX

#### *This is an individual activity.  I confirm that I made this exercise by myself.*

#### The dataset you are going to use for this activity is from the DOH COVID Data Drop dated January 29, 2022.  

#### *DOH_COVID_Data_Collect_Daily_Report.csv* contains self-reported inventories for the day from hospitals on COVID19-dedicated beds and mechanical ventilators.

#### 1. Import necessary libraries and Load the data set from the link given below into a pandas dataframe

In [1]:
# import the libraries
# your code starts here
import pandas as pd
# your code ends here

#read the data into the dataframe 
# your code starts here
df = pd.read_csv('DOH_COVID_Data_Collect_Daily_Report.csv')
# your code ends here

In [2]:
#
df

,hfhudcode,id,cfname,updateddate,addeddate,reportdate,icu_v,icu_o,isolbed_v,isolbed_o,...,trans_ttmf,discharged,region,region_psgc,province_psgc,city_mun_psgc,province,city_mun,north_coord,east_coord
0,DOH000000000032056,2412.0,"BINAKAYAN HOSPITAL AND MEDICAL CENTER, INC.",2020-07-03 17:32:06,2020-07-03 17:32:06,2020-07-03 00:00:00,0.0,0.0,0.0,0.0,...,0.0,1.0,REGION IV-A (CALABAR ZON),PH040000000,PH042100000,PH042111000,CAVITE,KAWIT,0.0,0.0
1,DOH000000000032056,4046.0,"BINAKAYAN HOSPITAL AND MEDICAL CENTER, INC.",2020-07-04 18:11:16,2020-07-04 18:11:16,2020-07-04 00:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,REGION IV-A (CALABAR ZON),PH040000000,PH042100000,PH042111000,CAVITE,KAWIT,0.0,0.0
2,DOH000000000032056,4942.0,"BINAKAYAN HOSPITAL AND MEDICAL CENTER, INC.",2020-07-05 10:05:44,2020-07-05 10:05:44,2020-07-05 00:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,REGION IV-A (CALABAR ZON),PH040000000,PH042100000,PH042111000,CAVITE,KAWIT,0.0,0.0
3,DOH000000000032056,7228.0,"BINAKAYAN HOSPITAL AND MEDICAL CENTER, INC.",2020-07-06 16:10:27,2020-07-06 16:10:27,2020-07-06 00:00:00,0.0,0.0,0.0,0.0,...,0.0,0.0,REGION IV-A (CALABAR ZON),PH040000000,PH042100000,PH042111000,CAVITE,KAWIT,0.0,0.0
4,DOH000000000032056,8607.0,"BINAKAYAN HOSPITAL AND MEDICAL CENTER, INC.",2020-07-07 12:24:28,2020-07-07 12:24:28,2020-07-07 00:00:00,0.0,0.0,2.0,5.0,...,0.0,0.0,REGION IV-A (CALABAR ZON),PH040000000,PH042100000,PH042111000,CAVITE,KAWIT,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743649,DOH000000000005695,688254.0,SOUTHWESTERN UNIVERSITY MEDICAL CENTER,2022-01-24 12:35:01,2022-01-24 12:35:01,2022-01-24 00:00:00,0.0,0.0,5.0,3.0,...,0.0,0.0,REGION VII (CENTRAL VISAYAS),PH070000000,PH072200000,PH072217000,CEBU,CEBU CITY (CAPITAL),0.0,0.0
743650,DOH000000000005695,690335.0,SOUTHWESTERN UNIVERSITY MEDICAL CENTER,2022-01-25 19:37:36,2022-01-25 19:37:36,2022-01-25 00:00:00,0.0,0.0,5.0,4.0,...,0.0,0.0,REGION VII (CENTRAL VISAYAS),PH070000000,PH072200000,PH072217000,CEBU,CEBU CITY (CAPITAL),0.0,0.0
743651,DOH000000000005695,691747.0,SOUTHWESTERN UNIVERSITY MEDICAL CENTER,2022-01-26 15:43:24,2022-01-26 15:43:24,2022-01-26 00:00:00,0.0,0.0,6.0,3.0,...,0.0,0.0,REGION VII (CENTRAL VISAYAS),PH070000000,PH072200000,PH072217000,CEBU,CEBU CITY (CAPITAL),0.0,0.0
743652,DOH000000000005695,693558.0,SOUTHWESTERN UNIVERSITY MEDICAL CENTER,2022-01-27 19:18:10,2022-01-27 19:18:10,2022-01-27 00:00:00,0.0,0.0,5.0,4.0,...,0.0,0.0,REGION VII (CENTRAL VISAYAS),PH070000000,PH072200000,PH072217000,CEBU,CEBU CITY (CAPITAL),0.0,0.0
743653,DOH000000000005695,693558.0,SOUTHWESTERN UNIVERSITY MEDICAL CENTER,2022-01-27 19:18:10,2022-01-27 19:18:10,2022-01-28 00:00:00,0.0,0.0,5.0,4.0,...,0.0,0.0,REGION VII (CENTRAL VISAYAS),PH070000000,PH072200000,PH072217000,CEBU,CEBU CITY (CAPITAL),0.0,0.0

#### 2. Feature overview

In [3]:
# Find the number of rows and columns 
# your code starts here
nrows, ncolumns = df.shape
print(nrows, ncolumns)
# your code ends here

743654 57

In [4]:
#Basic Statistics of each column
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
id,727092.0,294390.119182,1.997995e+05,1.0,126977.0,252422.0,461479.0,6.952880e+05
icu_v,727092.0,1.064505,4.706662e+00,0.0,0.0,0.0,0.0,2.450000e+02
icu_o,727092.0,1.134805,5.638081e+00,0.0,0.0,0.0,0.0,1.850000e+02
isolbed_v,727092.0,7.609087,1.858074e+01,0.0,0.0,3.0,9.0,6.760000e+02
isolbed_o,727092.0,5.942900,1.330871e+01,0.0,0.0,1.0,6.0,3.590000e+02
beds_ward_v,727092.0,4.563894,1.885052e+01,0.0,0.0,0.0,4.0,1.171000e+03
beds_ward_o,727092.0,3.342053,1.363637e+01,0.0,0.0,0.0,1.0,6.260000e+02
mechvent_v,727092.0,1.373671,4.283203e+00,0.0,0.0,0.0,1.0,4.200000e+02
mechvent_o,727092.0,0.636613,2.720969e+00,0.0,0.0,0.0,0.0,9.100000e+01
icu_v_nc,727092.0,2.597099,6.740511e+00,0.0,0.0,0.0,2.0,7.330000e+02
icu_o_nc,727092.0,2.415294,1.162370e+01,0.0,0.0,0.0,1.0,6.727000e+03
nonicu_v_nc,727092.0,27.473155,4.170942e+01,0.0,6.0,17.0,34.0,6.700000e+03
nonicu_o_nc,727092.0,32.328843,9.009524e+01,0.0,5.0,15.0,34.0,2.800000e+04
mechvent_v_nc,727092.0,1.859873,5.388945e+00,0.0,0.0,0.0,2.0,9.680000e+02
mechvent_o_nc,727092.0,1.102268,4.565917e+00,0.0,0.0,0.0,0.0,1.009000e+03
qnurse,724033.0,1.911990,1.161195e+01,0.0,0.0,0.0,0.0,8.170000e+02
qdoctor,724033.0,0.457507,2.448469e+00,0.0,0.0,0.0,0.0,9.000000e+01
qother,724033.0,1.559785,6.662734e+00,0.0,0.0,0.0,1.0,4.110000e+02
nurse_adm,724033.0,0.153123,1.007861e+00,0.0,0.0,0.0,0.0,3.930000e+02
doctor_adm,724033.0,0.042731,3.135692e-01,0.0,0.0,0.0,0.0,6.100000e+01
other_adm,724033.0,0.195846,1.261091e+00,0.0,0.0,0.0,0.0,2.700000e+02
susp_asym,727092.0,0.792209,5.910791e+00,0.0,0.0,0.0,0.0,7.500000e+02
susp_mild,727092.0,1.941688,5.589827e+00,0.0,0.0,0.0,2.0,4.430000e+02
susp_severe,727092.0,0.510050,3.524932e+00,0.0,0.0,0.0,0.0,2.130000e+02
susp_crit,727092.0,0.149234,1.027442e+00,0.0,0.0,0.0,0.0,2.310000e+02
susp_died,724033.0,0.064264,3.793282e-01,0.0,0.0,0.0,0.0,5.500000e+01
susp_mod,521447.0,1.269466,5.500088e+00,0.0,0.0,0.0,0.0,5.780000e+02
prob_asym,727092.0,0.141789,1.355282e+00,0.0,0.0,0.0,0.0,1.630000e+02
prob_mild,727092.0,0.541881,2.394872e+00,0.0,0.0,0.0,0.0,2.310000e+02
prob_severe,727092.0,0.161094,1.304613e+00,0.0,0.0,0.0,0.0,1.210000e+02
prob_crit,727092.0,0.047262,4.476373e-01,0.0,0.0,0.0,0.0,9.900000e+01
prob_died,724033.0,0.025484,2.388710e-01,0.0,0.0,0.0,0.0,1.500000e+01
prob_mod,521447.0,0.476998,2.507919e+00,0.0,0.0,0.0,0.0,2.270000e+02
conf_asym,727092.0,0.696707,4.583916e+00,0.0,0.0,0.0,0.0,4.990000e+02
conf_mild,727092.0,2.228835,7.877533e+00,0.0,0.0,0.0,1.0,4.430000e+02
conf_severe,727092.0,1.147119,5.487265e+00,0.0,0.0,0.0,0.0,2.110000e+02
conf_crit,727092.0,0.388764,2.361214e+00,0.0,0.0,0.0,0.0,1.200000e+02
conf_died,724033.0,0.019175,1.826286e-01,0.0,0.0,0.0,0.0,1.100000e+01
conf_mod,521447.0,2.475805,8.592215e+00,0.0,0.0,0.0,1.0,5.990000e+02
tpatient_adm,724033.0,3025.298814,2.523797e+06,0.0,9.0,21.0,49.0,2.147484e+09
tpatient_er,724033.0,19.057964,2.715382e+01,0.0,4.0,10.0,23.0,1.000000e+03
tpatient_icu,724033.0,2.648769,9.112502e+00,0.0,0.0,0.0,1.0,6.660000e+02
trans_ttmf,724033.0,0.083267,1.412354e+00,0.0,0.0,0.0,0.0,7.170000e+02
discharged,724033.0,0.833107,6.699899e+00,0.0,0.0,0.0,0.0,2.840000e+02
north_coord,743654.0,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00
east_coord,743654.0,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00

In [5]:
#Get the basic information of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 743654 entries, 0 to 743653
Data columns (total 57 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   hfhudcode      743654 non-null  object
 1   id             727092 non-null  float64
 2   cfname         743654 non-null  object
 3   updateddate    727092 non-null  object
 4   addeddate      727092 non-null  object
 5   reportdate     743654 non-null  object
 6   icu_v          727092 non-null  float64
 7   icu_o          727092 non-null  float64
 8   isolbed_v      727092 non-null  float64
 9   isolbed_o      727092 non-null  float64
 10  beds_ward_v    727092 non-null  float64
 11  beds_ward_o    727092 non-null  float64
 12  mechvent_v     727092 non-null  float64
 13  mechvent_o     727092 non-null  float64
 14  icu_v_nc       727092 non-null  float64
 15  icu_o_nc       727092 non-null  float64
 16  nonicu_v_nc    727092 non-null  float64
 17  nonicu_o_nc    727092 non-null  float64
 18  mechvent_v_nc  727092 non-null  float64
 19  mechvent_o_nc  727092 non-null  float64
 20  qnurse         724033 non-null  float64
 21  qdoctor        724033 non-null  float64
 22  qother         724033 non-null  float64
 23  nurse_adm      724033 non-null  float64
 24  doctor_adm     724033 non-null  float64
 25  other_adm      724033 non-null  float64
 26  susp_asym      727092 non-null  float64
 27  susp_mild      727092 non-null  float64
 28  susp_severe    727092 non-null  float64
 29  susp_crit      727092 non-null  float64
 30  susp_died      724033 non-null  float64
 31  susp_mod       521447 non-null  float64
 32  prob_asym      727092 non-null  float64
 33  prob_mild      727092 non-null  float64
 34  prob_severe    727092 non-null  float64
 35  prob_crit      727092 non-null  float64
 36  prob_died      724033 non-null  float64
 37  prob_mod       521447 non-null  float64
 38  conf_asym      727092 non-null  float64
 39  conf_mild      727092 non-null  float64
 40  conf_severe    727092 non-null  float64
 41  conf_crit      727092 non-null  float64
 42  conf_died      724033 non-null  float64
 43  conf_mod       521447 non-null  float64
 44  tpatient_adm   724033 non-null  float64
 45  tpatient_er    724033 non-null  float64
 46  tpatient_icu   724033 non-null  float64
 47  trans_ttmf     724033 non-null  float64
 48  discharged     724033 non-null  float64
 49  region         743654 non-null  object
 50  region_psgc    743654 non-null  object
 51  province_psgc  743654 non-null  object
 52  city_mun_psgc  743654 non-null  object
 53  province       743654 non-null  object
 54  city_mun       743654 non-null  object
 55  north_coord    743654 non-null  float64
 56  east_coord     743654 non-null  float64
dtypes: float64(46), object(11)
memory usage: 323.4+ MB

In [6]:
# Get the column names 
# your code starts here
df.columns
# your code ends here

Index(['hfhudcode', 'id', 'cfname', 'updateddate', 'addeddate', 'reportdate',
       'icu_v', 'icu_o', 'isolbed_v', 'isolbed_o', 'beds_ward_v',
       'beds_ward_o', 'mechvent_v', 'mechvent_o', 'icu_v_nc', 'icu_o_nc',
       'nonicu_v_nc', 'nonicu_o_nc', 'mechvent_v_nc', 'mechvent_o_nc',
       'qnurse', 'qdoctor', 'qother', 'nurse_adm', 'doctor_adm', 'other_adm',
       'susp_asym', 'susp_mild', 'susp_severe', 'susp_crit', 'susp_died',
       'susp_mod', 'prob_asym', 'prob_mild', 'prob_severe', 'prob_crit',
       'prob_died', 'prob_mod', 'conf_asym', 'conf_mild', 'conf_severe',
       'conf_crit', 'conf_died', 'conf_mod', 'tpatient_adm', 'tpatient_er',
       'tpatient_icu', 'trans_ttmf', 'discharged', 'region', 'region_psgc',
       'province_psgc', 'city_mun_psgc', 'province', 'city_mun', 'north_coord',
       'east_coord'],
      dtype='object')

#### 3. Remove unnecessary columns

In [7]:
df.shape

(743654, 57)

In [8]:
# Remove all date columns in place
# your code starts here
df.drop(['updateddate', 'addeddate', 'reportdate'], axis=1, inplace=True)
# your code ends here

In [9]:
df.shape

(743654, 54)

In [10]:
#
df

,hfhudcode,id,cfname,icu_v,icu_o,isolbed_v,isolbed_o,beds_ward_v,beds_ward_o,mechvent_v,...,trans_ttmf,discharged,region,region_psgc,province_psgc,city_mun_psgc,province,city_mun,north_coord,east_coord
0,DOH000000000032056,2412.0,"BINAKAYAN HOSPITAL AND MEDICAL CENTER, INC.",0.0,0.0,0.0,0.0,1.0,1.0,2.0,...,0.0,1.0,REGION IV-A (CALABAR ZON),PH040000000,PH042100000,PH042111000,CAVITE,KAWIT,0.0,0.0
1,DOH000000000032056,4046.0,"BINAKAYAN HOSPITAL AND MEDICAL CENTER, INC.",0.0,0.0,0.0,0.0,6.0,1.0,4.0,...,0.0,0.0,REGION IV-A (CALABAR ZON),PH040000000,PH042100000,PH042111000,CAVITE,KAWIT,0.0,0.0
2,DOH000000000032056,4942.0,"BINAKAYAN HOSPITAL AND MEDICAL CENTER, INC.",0.0,0.0,0.0,0.0,2.0,5.0,4.0,...,0.0,0.0,REGION IV-A (CALABAR ZON),PH040000000,PH042100000,PH042111000,CAVITE,KAWIT,0.0,0.0
3,DOH000000000032056,7228.0,"BINAKAYAN HOSPITAL AND MEDICAL CENTER, INC.",0.0,0.0,0.0,0.0,1.0,0.0,4.0,...,0.0,0.0,REGION IV-A (CALABAR ZON),PH040000000,PH042100000,PH042111000,CAVITE,KAWIT,0.0,0.0
4,DOH000000000032056,8607.0,"BINAKAYAN HOSPITAL AND MEDICAL CENTER, INC.",0.0,0.0,2.0,5.0,2.0,5.0,4.0,...,0.0,0.0,REGION IV-A (CALABAR ZON),PH040000000,PH042100000,PH042111000,CAVITE,KAWIT,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743649,DOH000000000005695,688254.0,SOUTHWESTERN UNIVERSITY MEDICAL CENTER,0.0,0.0,5.0,3.0,20.0,0.0,3.0,...,0.0,0.0,REGION VII (CENTRAL VISAYAS),PH070000000,PH072200000,PH072217000,CEBU,CEBU CITY (CAPITAL),0.0,0.0
743650,DOH000000000005695,690335.0,SOUTHWESTERN UNIVERSITY MEDICAL CENTER,0.0,0.0,5.0,4.0,20.0,0.0,3.0,...,0.0,0.0,REGION VII (CENTRAL VISAYAS),PH070000000,PH072200000,PH072217000,CEBU,CEBU CITY (CAPITAL),0.0,0.0
743651,DOH000000000005695,691747.0,SOUTHWESTERN UNIVERSITY MEDICAL CENTER,0.0,0.0,6.0,3.0,20.0,0.0,3.0,...,0.0,0.0,REGION VII (CENTRAL VISAYAS),PH070000000,PH072200000,PH072217000,CEBU,CEBU CITY (CAPITAL),0.0,0.0
743652,DOH000000000005695,693558.0,SOUTHWESTERN UNIVERSITY MEDICAL CENTER,0.0,0.0,5.0,4.0,20.0,0.0,3.0,...,0.0,0.0,REGION VII (CENTRAL VISAYAS),PH070000000,PH072200000,PH072217000,CEBU,CEBU CITY (CAPITAL),0.0,0.0
743653,DOH000000000005695,693558.0,SOUTHWESTERN UNIVERSITY MEDICAL CENTER,0.0,0.0,5.0,4.0,20.0,0.0,3.0,...,0.0,0.0,REGION VII (CENTRAL VISAYAS),PH070000000,PH072200000,PH072217000,CEBU,CEBU CITY (CAPITAL),0.0,0.0

In [11]:
# Remove (in place) all location related columns, except the "region" column. The "region" column remains in the dataframe.
# your code starts here
# df.columns[-7:]
not_needed_location_columns = [
    'region_psgc', 'province_psgc',
    'city_mun_psgc', 'province',
    'city_mun','north_coord', 
    'east_coord']

df.drop(not_needed_location_columns, axis=1, inplace=True)
df.drop('cfname', axis=1, inplace=True)  # Some facility names are related to location.
# your code ends here

In [12]:
df.shape

(743654, 46)

In [13]:
#
df

,hfhudcode,id,icu_v,icu_o,isolbed_v,isolbed_o,beds_ward_v,beds_ward_o,mechvent_v,mechvent_o,...,conf_severe,conf_crit,conf_died,conf_mod,tpatient_adm,tpatient_er,tpatient_icu,trans_ttmf,discharged,region
0,DOH000000000032056,2412.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,...,0.0,0.0,0.0,NaN,2.0,2.0,0.0,0.0,1.0,REGION IV-A (CALABAR ZON)
1,DOH000000000032056,4046.0,0.0,0.0,0.0,0.0,6.0,1.0,4.0,0.0,...,0.0,0.0,0.0,NaN,28.0,11.0,0.0,0.0,0.0,REGION IV-A (CALABAR ZON)
2,DOH000000000032056,4942.0,0.0,0.0,0.0,0.0,2.0,5.0,4.0,0.0,...,0.0,0.0,0.0,NaN,30.0,17.0,0.0,0.0,0.0,REGION IV-A (CALABAR ZON)
3,DOH000000000032056,7228.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,...,0.0,0.0,0.0,NaN,30.0,5.0,0.0,0.0,0.0,REGION IV-A (CALABAR ZON)
4,DOH000000000032056,8607.0,0.0,0.0,2.0,5.0,2.0,5.0,4.0,0.0,...,0.0,0.0,0.0,NaN,31.0,10.0,0.0,0.0,0.0,REGION IV-A (CALABAR ZON)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743649,DOH000000000005695,688254.0,0.0,0.0,5.0,3.0,20.0,0.0,3.0,1.0,...,0.0,0.0,0.0,3.0,38.0,6.0,1.0,0.0,0.0,REGION VII (CENTRAL VISAYAS)
743650,DOH000000000005695,690335.0,0.0,0.0,5.0,4.0,20.0,0.0,3.0,1.0,...,0.0,0.0,0.0,4.0,38.0,6.0,1.0,0.0,0.0,REGION VII (CENTRAL VISAYAS)
743651,DOH000000000005695,691747.0,0.0,0.0,6.0,3.0,20.0,0.0,3.0,1.0,...,0.0,0.0,0.0,3.0,38.0,6.0,1.0,0.0,0.0,REGION VII (CENTRAL VISAYAS)
743652,DOH000000000005695,693558.0,0.0,0.0,5.0,4.0,20.0,0.0,3.0,1.0,...,0.0,0.0,0.0,5.0,38.0,6.0,1.0,0.0,0.0,REGION VII (CENTRAL VISAYAS)
743653,DOH000000000005695,693558.0,0.0,0.0,5.0,4.0,20.0,0.0,3.0,1.0,...,0.0,0.0,0.0,5.0,38.0,6.0,1.0,0.0,0.0,REGION VII (CENTRAL VISAYAS)

In [14]:
# Remove (in place) all columns with high cardinality.
# your code starts here
threshold = 100  # Arbitrarily selected based from my experience.

for column_name in df.columns:
    if df[column_name].nunique() > threshold:
        df.drop(column_name, axis=1, inplace=True)

print(df.nunique())
df
# your code ends here

mechvent_v     82
mechvent_o     70
qdoctor        78
nurse_adm      54
doctor_adm     23
other_adm      65
susp_crit      46
susp_died      14
prob_asym      83
prob_mild      88
prob_severe    59
prob_crit      27
prob_died      14
prob_mod       92
conf_died      10
trans_ttmf     65
region         18
dtype: int64

,mechvent_v,mechvent_o,qdoctor,nurse_adm,doctor_adm,other_adm,susp_crit,susp_died,prob_asym,prob_mild,prob_severe,prob_crit,prob_died,prob_mod,conf_died,trans_ttmf,region
0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,REGION IV-A (CALABAR ZON)
1,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,REGION IV-A (CALABAR ZON)
2,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,REGION IV-A (CALABAR ZON)
3,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,REGION IV-A (CALABAR ZON)
4,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,NaN,0.0,0.0,REGION IV-A (CALABAR ZON)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743649,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,REGION VII (CENTRAL VISAYAS)
743650,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,REGION VII (CENTRAL VISAYAS)
743651,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,REGION VII (CENTRAL VISAYAS)
743652,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,REGION VII (CENTRAL VISAYAS)
743653,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,REGION VII (CENTRAL VISAYAS)

In [15]:
df.shape

(743654, 17)

#### 4. Handling missing data
#### If column contains more than 70% null values, remove that column.  Otherwise, remove rows with null values.

In [16]:
#remove Null values
# your code starts here
for column_name in df.columns:
    if (df[column_name].isna().sum() / nrows) > 0.7:
        df.drop(column_name, axis=1, inplace=True)
        
df = df.dropna()
# your code ends here

#Get total number of null in each column
# your code starts here
df.isna().sum()
# your code ends here

mechvent_v     0
mechvent_o     0
qdoctor        0
nurse_adm      0
doctor_adm     0
other_adm      0
susp_crit      0
susp_died      0
prob_asym      0
prob_mild      0
prob_severe    0
prob_crit      0
prob_died      0
prob_mod       0
conf_died      0
trans_ttmf     0
region         0
dtype: int64

In [17]:
df.shape

(518388, 17)

#### See the huge amount of data you have removed. Thus, removing rows with null values may not be the best way to handle missing data.

#### 5. Frequency distribution of Region column

In [18]:
# get the frequency distribution of the Region column
# your code starts here
df['region'].value_counts()
# your code ends here

REGION IV-A (CALABAR ZON)                      86572
REGION III (CENTRAL LUZON)                     70272
NATIONAL CAPITAL REGION (NCR)                  65379
REGION I (ILOCOS REGION)                       32693
REGION X (NORTHERN MINDANAO)                   29909
REGION VI (WESTERN VISAYAS)                    26910
REGION II (CAGAYAN VALLEY)                     26496
REGION XII (SOCCSKSA RGEN)                     26078
REGION XI (DAVAO REGION)                       24356
REGION VII (CENTRAL VISAYAS)                   23466
REGION V (BICOL REGION)                        22741
REGION VIII (EASTERN VISAYAS)                  21039
REGION IX (ZAMBOANGA PENINSULA)                17340
REGION IV-B (MIMAROPA)                         12834
CORDILLERA ADMINISTRA TIVE REGION (CAR)        11571
REGION XIII (CARAGA)                            9468
AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)     9242
BARMM                                           2022
Name: region, dtype: int64

#### 6. Instead of by Region, you prefer to analyze the data by island group, Luzon-Visayas-Mindanao (LVM).

In [19]:
# Add a new column named "LVM" to df.
# your code starts here
pd.options.mode.chained_assignment = None  # default='warn'
df['LVM'] = df['region']
# your code ends here

In [20]:
df.head()

,mechvent_v,mechvent_o,qdoctor,nurse_adm,doctor_adm,other_adm,susp_crit,susp_died,prob_asym,prob_mild,prob_severe,prob_crit,prob_died,prob_mod,conf_died,trans_ttmf,region,LVM
161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,REGION IV-A (CALABAR ZON),REGION IV-A (CALABAR ZON)
162,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,REGION IV-A (CALABAR ZON),REGION IV-A (CALABAR ZON)
163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,REGION IV-A (CALABAR ZON),REGION IV-A (CALABAR ZON)
164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,REGION IV-A (CALABAR ZON),REGION IV-A (CALABAR ZON)
165,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,REGION IV-A (CALABAR ZON),REGION IV-A (CALABAR ZON)

In [21]:
# Update the LVM column by grouping the regions to Luzon, Visayas, Mindanao 
# You can use replace function from pandas
# your code starts here
# Reference: https://www.philatlas.com/regions.html
region_to_LVM_mapping = {
    'REGION I (ILOCOS REGION)': 'Luzon',
    'REGION II (CAGAYAN VALLEY)': 'Luzon',
    'REGION III (CENTRAL LUZON)':  'Luzon',
    'REGION IV-A (CALABAR ZON)': 'Luzon',
    'REGION IV-B (MIMAROPA)': 'Luzon',
    'REGION V (BICOL REGION)': 'Luzon',
    'CORDILLERA ADMINISTRA TIVE REGION (CAR)': 'Luzon',
    'NATIONAL CAPITAL REGION (NCR)': 'Luzon',
    'REGION VI (WESTERN VISAYAS)': 'Visayas',
    'REGION VII (CENTRAL VISAYAS)': 'Visayas',
    'REGION VIII (EASTERN VISAYAS)': 'Visayas',
    'REGION IX (ZAMBOANGA PENINSULA)': 'Mindanao',
    'REGION X (NORTHERN MINDANAO)': 'Mindanao',
    'REGION XI (DAVAO REGION)': 'Mindanao',
    'REGION XII (SOCCSKSA RGEN)': 'Mindanao',
    'REGION XIII (CARAGA)': 'Mindanao',
    'AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)': 'Mindanao',
    'BARMM': 'Mindanao'
}

df['LVM'].replace(region_to_LVM_mapping, inplace=True)
# your code ends here

In [22]:
# After grouping, this is the column
df["LVM"].unique()

array(['Luzon', 'Mindanao', 'Visayas'], dtype=object)

In [23]:
# Remove (in place) the region column.
# your code starts here
df.drop('region', axis=1, inplace=True)
# your code ends here

In [24]:
df.head()

,mechvent_v,mechvent_o,qdoctor,nurse_adm,doctor_adm,other_adm,susp_crit,susp_died,prob_asym,prob_mild,prob_severe,prob_crit,prob_died,prob_mod,conf_died,trans_ttmf,LVM
161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Luzon
162,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Luzon
163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Luzon
164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Luzon
165,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Luzon

#### 7. Select and perform a suitable encoding method for the data (2 points)

In [25]:
# your code starts here
import numpy as np
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

data_column_category = df.select_dtypes(exclude=[np.number]).columns
for column_name in data_column_category:
    df[column_name] = label_encoder.fit_transform(df[column_name])

df
# your code ends here

,mechvent_v,mechvent_o,qdoctor,nurse_adm,doctor_adm,other_adm,susp_crit,susp_died,prob_asym,prob_mild,prob_severe,prob_crit,prob_died,prob_mod,conf_died,trans_ttmf,LVM
161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
162,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
165,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743649,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
743650,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
743651,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
743652,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
743653,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2

#### 8. Perform the standard scaling. (2 points)

In [26]:
# your code starts here
from sklearn.preprocessing import StandardScaler

std_scale = StandardScaler().fit_transform(df)
scaled_frame = pd.DataFrame(std_scale, columns = df.columns)

df = scaled_frame
df
# your code ends here

,mechvent_v,mechvent_o,qdoctor,nurse_adm,doctor_adm,other_adm,susp_crit,susp_died,prob_asym,prob_mild,prob_severe,prob_crit,prob_died,prob_mod,conf_died,trans_ttmf,LVM
0,-0.330686,-0.243059,-0.183047,-0.176929,-0.160597,-0.159627,-0.146162,-0.174291,-0.101008,-0.231553,-0.123124,-0.102756,-0.108252,-0.189243,-0.096725,-0.102608,-0.695187
1,-0.330686,-0.243059,-0.183047,-0.176929,-0.160597,-0.159627,-0.146162,-0.174291,-0.101008,-0.231553,-0.123124,-0.102756,-0.108252,-0.189243,-0.096725,-0.102608,-0.695187
2,-0.330686,-0.243059,-0.183047,-0.176929,-0.160597,-0.159627,-0.146162,-0.174291,-0.101008,-0.231553,-0.123124,-0.102756,-0.108252,-0.189243,-0.096725,-0.102608,-0.695187
3,-0.330686,-0.243059,-0.183047,-0.176929,-0.160597,-0.159627,-0.146162,-0.174291,-0.101008,-0.231553,-0.123124,-0.102756,-0.108252,-0.189243,-0.096725,-0.102608,-0.695187
4,0.591339,-0.243059,-0.183047,-0.176929,-0.160597,-0.159627,-0.146162,-0.174291,-0.101008,-0.231553,-0.123124,-0.102756,-0.108252,-0.189243,-0.096725,-0.102608,-0.695187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518383,0.360833,0.090495,-0.183047,-0.176929,-0.160597,-0.159627,-0.146162,-0.174291,-0.101008,-0.231553,-0.123124,-0.102756,-0.108252,-0.189243,-0.096725,-0.102608,2.063731
518384,0.360833,0.090495,-0.183047,-0.176929,-0.160597,-0.159627,-0.146162,-0.174291,-0.101008,-0.231553,-0.123124,-0.102756,-0.108252,-0.189243,-0.096725,-0.102608,2.063731
518385,0.360833,0.090495,-0.183047,-0.176929,-0.160597,-0.159627,-0.146162,-0.174291,-0.101008,-0.231553,-0.123124,-0.102756,-0.108252,-0.189243,-0.096725,-0.102608,2.063731
518386,0.360833,0.090495,-0.183047,-0.176929,-0.160597,-0.159627,-0.146162,-0.174291,-0.101008,-0.231553,-0.123124,-0.102756,-0.108252,-0.189243,-0.096725,-0.102608,2.063731
518387,0.360833,0.090495,-0.183047,-0.176929,-0.160597,-0.159627,-0.146162,-0.174291,-0.101008,-0.231553,-0.123124,-0.102756,-0.108252,-0.189243,-0.096725,-0.102608,2.063731